name: Update data
on:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ghtopdep
        run: |
          pipx install git+https://github.com/haya14busa/ghtopdep.git#egg=ghtopdep
      - run: |
          ghtopdep --json --rows 100 https://github.com/reviewdog/action-setup
