name: Update data
on:
  schedule:
  - cron: "14 7 * * 0"
  repository_dispatch:
    types: [updates]
  workflow_dispatch:
  push:
    branches:
      - fix-script

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: main
      # - name: Install ghtopdep
      #   run: |
      #     pipx install git+https://github.com/haya14busa/ghtopdep.git#egg=ghtopdep
      - uses: aquaproj/aqua-installer@v0.6.0
        with:
          aqua_version: v2.29.0
      - run: ./update.sh
      - run: ./update_shieldsio_all.sh
      - run: ./update_repo_templates_all.sh
      - run: ./update_top_readme.sh
      - run: ./update_owner_page_all.sh
      - name: Commit and Push
        run: |
          # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git config core.filemode false
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --exit-code --quiet
          then
            git commit -m "Update GitHub Used-By data"
            git push origin main
          fi
